version: "3.8"
services:

  db:
    container_name: houseav_db
    image: postgres
    volumes:
      - ./houseav_pgdata:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_USER: lucas
      POSTGRES_PASSWORD: password
      POSTGRES_DB: houseavdb
    ports:
      - "5432:5432"

  pgadmin:
    container_name: houseav_pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"

  # nestjs:
  #   container_name: houseav_backend_api
  #   build: 
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - "1999:3000"

volumes:
  houseav_pgdata: