INSERT INTO public."Church" (id, "name", address) VALUES
(nextval('public."Church_id_seq"'), 'Adi Beinasco', 'Via Silvio Pellico, 6, 10092 Beinasco TO'),
(nextval('public."Church_id_seq"'), 'Adi Carmagnola', 'Via Rio Tercero, 24, 10022 Carmagnola TO'),
(nextval('public."Church_id_seq"'), 'Adi Chiavari', 'Via Colonnello Enrico Franceschi, 16043 Chiavari GE'),
(nextval('public."Church_id_seq"'), 'Adi Novara', 'Via Nino Oxilia, 4, 28100 Novara NO'),
(nextval('public."Church_id_seq"'), 'Adi Reggio Emilia', 'Via Bligny, 7, 42124 Reggio nell''Emilia RE'),
(nextval('public."Church_id_seq"'), 'Alfo & Omega Roma', 'Viale Giorgio De Chirico, 73, 00155 Roma RM'),
(nextval('public."Church_id_seq"'), 'Bethel Bari', '70132 Bari, Metropolitan City of Bari'),
(nextval('public."Church_id_seq"'), 'Bethel Cosenza', 'Via Popilia, 630, 87100 Cosenza CS'),
(nextval('public."Church_id_seq"'), 'Centro Uria', 'SP34, 15, 80014 Giugliano in Campania NA'),
(nextval('public."Church_id_seq"'), 'Chiesa Evangelica della Riconciliazione Genova', 'Via Digione, 24 rosso, 16126 Genova GE'),
(nextval('public."Church_id_seq"'), 'Chiesa Evangelica della Riconciliazione Milano', 'Via Privata Umberto Masotto, 9, 20133 Milano MI'),
(nextval('public."Church_id_seq"'), 'Chiesa Evangelica della Riconciliazione Torino', 'Via Torino, 34, 10044 Pianezza TO'),
(nextval('public."Church_id_seq"'), 'Chiesa Oasi', 'Via 1º Maggio, 33, 28053 Castelletto sopra Ticino NO'),
(nextval('public."Church_id_seq"'), 'Condividere Gesù', 'Via Re Pietro IV, 92100 Agrigento AG'),
(nextval('public."Church_id_seq"'), 'Elevation Church Enna', '94100 Enna, Free municipal consortium of Enna'),
(nextval('public."Church_id_seq"'), 'Gospel forum Bologna', 'Via Giuseppe Brini, 47, 40128 Bologna BO'),
(nextval('public."Church_id_seq"'), 'Gospel forum Cosenza', ''),
(nextval('public."Church_id_seq"'), 'Hope church', ''),
(nextval('public."Church_id_seq"'), 'Jesus Church Oslo', 'Markus Kirke, Schwensens gate 9c, 0170 Oslo, Norway'),
(nextval('public."Church_id_seq"'), 'New life Church Verbania', 'Via Belgio, 4, 28922 Pallanza VB'),
(nextval('public."Church_id_seq"'), 'PDG Palermo', 'Via de Grossis Carlo, 2h, 90135 Palermo PA'),
(nextval('public."Church_id_seq"'), 'PDG Desenzano', 'Via Mapella, 7, 25017 Lonato del Garda BS'),
(nextval('public."Church_id_seq"'), 'PDG Lavagna', 'Via Moggia, 75, 16033 Lavagna GE'),
(nextval('public."Church_id_seq"'), 'PDG Roma', 'Via Pietro Fumaroli, 14, 00155 Roma RM'),
(nextval('public."Church_id_seq"'), 'PDG Roma Est', 'Via Silicella, 113, 00169 Roma RM'),
(nextval('public."Church_id_seq"'), 'Pienovangelo Trani', 'Via Papa Giovanni XXIII, 81, 76125 Trani BT'),
(nextval('public."Church_id_seq"'), 'Sabaoth Alessandria', 'Via della Chimica, 15121 Zona Artigianale D3 AL'),
(nextval('public."Church_id_seq"'), 'Sabaoth Alba', 'Via Carmagnola, 6, 12050 Castelrotto CN'),
(nextval('public."Church_id_seq"'), 'Sabaoth Aragona', ''),
(nextval('public."Church_id_seq"'), 'Sabaoth Aosta', 'Frazione Plan Felinaz, 29, 11020 Charvensod AO'),
(nextval('public."Church_id_seq"'), 'Sabaoth Asti', ''),
(nextval('public."Church_id_seq"'), 'Sabaoth Bad Säckingen', 'Alte Basler Str. 12, 79713 Bad Säckingen, Germany'),
(nextval('public."Church_id_seq"'), 'Sabaoth Benevento', ''),
(nextval('public."Church_id_seq"'), 'Sabaoth Bergamo', 'Via delle Querce, 7, 24048 Treviolo BG'),
(nextval('public."Church_id_seq"'), 'Sabaoth Biella', 'Via Felice Piacenza, 32, 13900 Biella BI'),
(nextval('public."Church_id_seq"'), 'Sabaoth Bogotà', 'Cl. 72 #20c-54, Bogotá, Colombia'),
(nextval('public."Church_id_seq"'), 'Sabaoth Brescia', 'Via Arcangelo Tadini, 49, 25125 Brescia BS'),
(nextval('public."Church_id_seq"'), 'Sabaoth Busto Arsizio', 'Via Fulvio Testi, 5, 21052 Busto Arsizio VA'),
(nextval('public."Church_id_seq"'), 'Sabaoth Campinas', 'Av. Papa Paulo VI, 462 - Jardim do Trevo, Campinas - SP, 13030-150, Brazil'),
(nextval('public."Church_id_seq"'), 'Sabaoth Casale Monferrato', 'Sabaoth Casale Monferrato'),
(nextval('public."Church_id_seq"'), 'Sabaoth Catania', 'V.le Alcide De Gasperi, 42, 95127 Catania CT'),
(nextval('public."Church_id_seq"'), 'Sabaoth Cesena', ''),
(nextval('public."Church_id_seq"'), 'Sabaoth Como', 'Via Bonifacio da Modena, 1, 22100 Como CO'),
(nextval('public."Church_id_seq"'), 'Sabaoth Corigliano-Rossano', ''),
(nextval('public."Church_id_seq"'), 'Sabaoth Crema', 'Viale Alcide De Gasperi, 56B, 26013 Crema CR'),
(nextval('public."Church_id_seq"'), 'Sabaoth Cuneo', 'Via Benedetto Dalmastro, 13, 12100 Cuneo CN'),
(nextval('public."Church_id_seq"'), 'Sabaoth Dolomiti', 'Via Roma, 127, 32013 Longarone BL'),
(nextval('public."Church_id_seq"'), 'Sabaoth Elbasan - Albania', '8RJ7+9RC, Rruga Sulejman Pasha, Tirana, Albania'),
(nextval('public."Church_id_seq"'), 'Sabaoth Firenze', 'Via Galileo Galilei, 26, 50041 Calenzano FI'),
(nextval('public."Church_id_seq"'), 'Sabaoth Fondi', ''),
(nextval('public."Church_id_seq"'), 'Sabaoth Latina', 'Str. Bassianese, 1132, 04100 Latina LT'),
(nextval('public."Church_id_seq"'), 'Sabaoth Floripa', 'R. Santo Amaro, 155 - Estreito, Florianópolis - SC, 88075-510, Brazil'),
(nextval('public."Church_id_seq"'), 'Sabaoth Gela', '3828+67, 93012 Gela CL'),
(nextval('public."Church_id_seq"'), 'Sabaoth Genova', ''),
(nextval('public."Church_id_seq"'), 'Sabaoth Loano', '17025 Loano, Province of Savona'),
(nextval('public."Church_id_seq"'), 'Sabaoth Ginevra', ''),
(nextval('public."Church_id_seq"'), 'Sabaoth Konstanz', ''),
(nextval('public."Church_id_seq"'), 'Sabaoth Lecce', ''),
(nextval('public."Church_id_seq"'), 'Sabaoth Legnago', 'Via Casette, 40, 37045 Legnago VR'),
(nextval('public."Church_id_seq"'), 'Sabaoth Lugano', 'Via Trevano 63, 6900 Lugano, Switzerland'),
(nextval('public."Church_id_seq"'), 'Sabaoth Lushnie', ''),
(nextval('public."Church_id_seq"'), 'Sabaoth Mantova', 'Via Iº Maggio, 7c, 46030 San Giorgio Bigarello MN'),
(nextval('public."Church_id_seq"'), 'Sabaoth Milano', 'Via Privata Rosalba Carriera, 11, 20146 Milano MI'),
(nextval('public."Church_id_seq"'), 'Sabaoth Modena', 'Via Luigi Cherubini, 35, 41122 Modena MO'),
(nextval('public."Church_id_seq"'), 'Sabaoth Monza', 'Via Mentana, 20, 20900 Monza MB'),
(nextval('public."Church_id_seq"'), 'Sabaoth Napoli', 'Via Saverio Gatto, 47, 80131 Napoli NA'),
(nextval('public."Church_id_seq"'), 'Sabaoth Novara', ''),
(nextval('public."Church_id_seq"'), 'Sabaoth Vimercate', 'Via S. M. Molgora, 60/A, 20871 Vimercate MB'),
(nextval('public."Church_id_seq"'), 'Sabaoth Olbia', 'Via Capo Verde, 12, sett, 4, 07026 Olbia SS'),
(nextval('public."Church_id_seq"'), 'Sabaoth Padova', 'Via Pietro Martire Vermigli, 13, 35129 Padova PD'),
(nextval('public."Church_id_seq"'), 'Sabaoth Palermo', 'Via dei Peloritani, 24, 90144 Palermo PA'),
(nextval('public."Church_id_seq"'), 'Sabaoth Piombino', 'Via del Desco, 17, 57025 Piombino LI'),
(nextval('public."Church_id_seq"'), 'Sabaoth Pisa', 'Via Giosuè Carducci, 62H, 56010 Ghezzano PI'),
(nextval('public."Church_id_seq"'), 'Sabaoth Reggio Calabria', 'Via Nazionale Pentimele, 36, 89121 Reggio di Calabria RC'),
(nextval('public."Church_id_seq"'), 'Sabaoth Rivarolo', 'C.so Indipendenza, 76, 10086 Rivarolo Canavese TO'),
(nextval('public."Church_id_seq"'), 'Sabaoth Roma', 'Via Prenestina, 64, 00176 Roma RM'),
(nextval('public."Church_id_seq"'), 'Sabaoth Stoccolma', ''),
(nextval('public."Church_id_seq"'), 'Sabaoth Stuttgart', ''),
(nextval('public."Church_id_seq"'), 'Sabaoth Taranto', ''),
(nextval('public."Church_id_seq"'), 'Sabaoth Torino', 'Via Don Ettore Gaia, 17, 10043 Cascina Mellano TO'),
(nextval('public."Church_id_seq"'), 'Sabaoth Valona', ''),
(nextval('public."Church_id_seq"'), 'Sabaoth Venezia', ''),
(nextval('public."Church_id_seq"'), 'Sabaoth Verona', 'Via dell'' Artigianato, 1B, 37135 Verona VR'),
(nextval('public."Church_id_seq"'), 'Sabaoth Vila Velha', 'Av. América, 485 - Cristóvão Colombo, Vila Velha - ES, 29106-595, Brazil'),
(nextval('public."Church_id_seq"'), 'Sabaoth Vittoria', ''),
(nextval('public."Church_id_seq"'), 'Sorgente Di Vita', 'Via Pisa, 200, 20099 Sesto San Giovanni MI'),
(nextval('public."Church_id_seq"'), 'Vive Milano', 'Via Chiese, 60, 20126 Milano MI'),
(nextval('public."Church_id_seq"'), 'Vive Roma', 'Via Alberto Lionello, 201, 00139 Roma RM');
