name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    env:
      NODE_ENV: development
      AUTH_SECRET: ${{ secrets.AUTH_SECRET }}
      AUTH_SECRET_REFRESH: ${{ secrets.AUTH_SECRET_REFRESH }}
      PORT: ${{ secrets.PORT }}
      AUTH_DURATION: ${{ secrets.AUTH_DURATION }}
      AUTH_DURATION_REFRESH: ${{ secrets.AUTH_DURATION_REFRESH }}

      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: password
      DATABASE_NAME: houseavdb
      DATABASE_URI: postgresql://postgres:password@postgres:5432/houseavdb
      DATABASE_SYNCHRONIZE: 'true'
      DATABASE_LOGGING: 'true'

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: houseavdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5      

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Use Node.js 22
        uses: actions/setup-node@v3
        with:
          node-version: '22.2.0'

      - name: Install dependencies
        run: npm ci --include=dev

      - name: Lint code
        run: npm run lint

      - name: Build app
        run: npm run build

      - name: Run unit tests
        run: npm run test

      # - name: Run e2e tests
      #   run: npm run test:e2e
