name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    env:
      NODE_ENV: production
      AUTH_SECRET: ${{ secrets.AUTH_SECRET }}
      AUTH_SECRET_REFRESH: ${{ secrets.AUTH_SECRET_REFRESH }}
      DATABASE_USERNAME: ${{ secrets.DATABASE_USERNAME }}
      DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
      DATABASE_HOST: ${{ secrets.DATABASE_HOST }}
      DATABASE_URI: ${{ secrets.DATABASE_URI }}
      DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
      DATABASE_SYNCHRONIZE: ${{ secrets.DATABASE_SYNCHRONIZE }}
      DATABASE_LOGGING: ${{ secrets.DATABASE_LOGGING }}
      PORT: ${{ secrets.PORT }}
      AUTH_DURATION: ${{ secrets.AUTH_DURATION }}
      AUTH_DURATION_REFRESH: ${{ secrets.AUTH_DURATION_REFRESH }}
      VITE_USER_QUEUE_REGISTRATION: ${{ secrets.VITE_USER_QUEUE_REGISTRATION }}
      VITE_USER_QUEUE_REGISTRATION_KEY: ${{ secrets.VITE_USER_QUEUE_REGISTRATION_KEY }}
      VITE_SEC_ALGORITHM: ${{ secrets.VITE_SEC_ALGORITHM }}
      VITE_SEC_HASH: ${{ secrets.VITE_SEC_HASH }}
      VITE_SEC_KEY_SIZE: ${{ secrets.VITE_SEC_KEY_SIZE }}
      VITE_SEC_ITERATION_COUNT: ${{ secrets.VITE_SEC_ITERATION_COUNT }}
      ADMIN_PSWD: ${{ secrets.ADMIN_PSWD }}
      ADMIN_MAIL: ${{ secrets.ADMIN_MAIL }}
      MAILGUN_API_KEY: ${{ secrets.MAILGUN_API_KEY }}

    steps:
      # Step 1: Check out the code
      - name: Check out repository
        uses: actions/checkout@v2

      # Step 2: Set up Node.js
      - name: Use Node.js 22
        uses: actions/setup-node@v3
        with:
          node-version: '22.2.0'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm ci

      # Step 4: Lint code (optional)
      - name: Lint code
        run: npm run lint

      # Step 5: Build the app (optional if you need to build before tests)
      - name: Build app
        run: npm run build

      # Step 6: Run unit tests
      - name: Run unit tests
        run: npm run test

      # Step 7 (optional): Run E2E tests
      - name: Run e2e tests
        run: npm run test:e2e
